POST http://localhost:4004/catalog/modifyTask
Content-Type: application/json


{
  "ID": "19000254-263d-4bd2-ad5f-15d65a564253",
  "titulo": "atv7",
  "descricao": "Atividade Numero 7"
}

GET http://localhost:4004/catalog/Tasks


GET http://localhost:4004/catalog/listUserTask?userID=2287733e-f9c2-4f3d-acd1-194b69409d4b
