# ATV1


# POST http://localhost:4004/odata/v4/catalog/Games
# Content-Type: application/json


# {
#   "title": "Game4",
#   "price": 40,
#   "stock": 40,
#   "releaseDate": "2009-05-20",
#   "developer": {
#     "ID": "a0c5e580-6c62-47e6-bc46-9d0e7d4948e6"
#   }
# }


# POST http://localhost:4004/odata/v4/catalog/Developers
# Content-Type: application/json

# {
#   "name": "Creater3",
#   "creationYear": 2010
# }\



# ATV2

GET  http://localhost:4004/odata/v4/catalog/TaskService

POST http://localhost:4004/odata/v4/catalog/TaskService
Content-Type: application/json


{
  "titulo": "atv1",
  "descricao": "Atividade Numero 1",
  "concluida": 1,
  "data_criacao": "2025-12-10"
}


PATCH http://localhost:4004/odata/v4/catalog/TaskService/26279a39-d084-4509-a7c0-a320d81408bf
Content-Type: application/json

{
  "titulo": "Atividade1"
}

DELETE http://localhost:4004/odata/v4/catalog/TaskService/26279a39-d084-4509-a7c0-a320d81408bf