
//FILTER
GET http://localhost:4004/catalog/Tasks?$filter=titulo eq 'atv2'

# ORDER BY

GET http://localhost:4004/catalog/Tasks?$orderby=titulo desc


# COUNT

GET http://localhost:4004/catalog/Tasks?$count=true


# TOP and SKIP

GET http://localhost:4004/catalog/Tasks?$count=true&$top=2&$skip=1


# EXPAND

GET http://localhost:4004/catalog/Tasks?$expand=user


# SELECT

GET http://localhost:4004/catalog/Tasks?$select=titulo,descricao


# SELECT with EXPAND

GET http://localhost:4004/catalog/Tasks?$expand=user($select=name,email)